name: check-merge-request

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install all dependencies
        run: yarn install --frozen-lockfile
      - name: Run linting
        run: yarn lint

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install all dependencies
        run: yarn install --frozen-lockfile
      - name: Run build
        run: yarn build
